export {default as mainBack} from './mainBack.jpg'
export {default as portImg} from './PortImg.jpg'
export {default as socialAttack} from './5-social-engineering-attacks.png'
export {default as profileBG} from './profile-bg.png'
export {default as title} from './title.png'